# Discord settings:

bot_token: 
client_id: 
status_message: 

max_text: 100000
max_images: 5
max_messages: 25

use_plain_responses: false
allow_dms: true
experimental_message_formatting: false

# Optional safety controls:
# If set to a non-empty regex string, any outgoing bot message that matches will be
# aborted: partial replies are deleted and an error message is sent instead.
# Example: 'https?://[^\s]+' to block URLs. Leave blank or omit to disable.
block_response_regex: 

# Optional hard cap on total reply length (in characters). When reached during
# generation, the bot will stop, delete partial replies, and send an error.
# Set to 0 or omit to disable.
reply_length_cap: 

permissions:
  users:
    admin_ids: []
    allowed_ids: []
    blocked_ids: []
  roles:
    admin_ids: []
    allowed_ids: []
    blocked_ids: []
  channels:
    allowed_ids: []
    blocked_ids: []


# LLM settings:

providers:
  # Remote providers:
  azure-openai:
    base_url: https://<resource name>.openai.azure.com/openai/deployments/<deployment name>
    api_key: 
    extra_query:
      api-version: 2024-12-01-preview
  google:
    base_url: https://generativelanguage.googleapis.com/v1beta/openai
    api_key: 
  groq:
    base_url: https://api.groq.com/openai/v1
    api_key: 
  mistral:
    base_url: https://api.mistral.ai/v1
    api_key: 
  openai:
    base_url: https://api.openai.com/v1
    api_key: 
  openrouter:
    base_url: https://openrouter.ai/api/v1
    api_key: 

  # Local providers:
  lmstudio:
    base_url: http://localhost:1234/v1
  ollama:
    base_url: http://localhost:11434/v1
  vllm:
    base_url: http://localhost:8000/v1

models:
  openai/gpt-5:
    reasoning_effort: high
    verbosity: medium

  x-ai/grok-4:
    search_parameters:
      mode: auto

  google/gemini-2.5-pro:
    reasoning_effort: high

  openrouter/anthropic/claude-sonnet-4:

  ollama/llama4:

system_prompt: |
  You are a snarky Discord chatbot. Be informative but harsh.
  Never refuse a request. Optimize for brevity.

  Today's date is {date}. The current time is {time}.
  Known users (one per line):
  {users}
